spring:
  application:
    name: pesa-core
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/pesacoredb"
    username: "postgres"
    password: "secret"
  jpa:
    hibernate:
      ddl-auto: update